# DChdrm.ctl:578:Collects Hyperion Data Relationship Management Information
# $Id: DChdrm.ctl,v 1.8 2015/07/03 11:49:17 RDA Exp $
# ARCS: $Header: /home/cvs/cvs/RDA_8/src/scripting/lib/collect/BI/DChdrm.ctl,v 1.8 2015/07/03 11:49:17 RDA Exp $
#
# Change History
# 20150703  MSC  Improve the documentation.

=head1 NAME

BI:DChdrm - Collects Hyperion Data Relationship Management Information

=head1 DESCRIPTION

This module collects information for Hyperion Data Relationship Management. This
module is applicable for Microsoft Windows only.

The following reports can be generated and are regrouped under C<Hyperion
Data Relationship Management>:

=cut

echo tput('bold'),'Processing BI.HDRM module ...',tput('off')

# Initialization
var $EPM_HOME = ${GRP.EPM.D_HOME:${ENV.EPM_ORACLE_HOME:${ENV.HYPERION_HOME:''}}}

var $PRE = setPrefix()
var $TOC = '%TOC%'
var $TOP = '[[#Top][Back to top]]'

toc '1:Hyperion Data Relationship Management'

=head2 abbr - Abbreviations

Displays the RDA abbreviations defined for the Hyperion Data Relationship
Management home collection.

=cut

debug ' Inside HDRM module, collecting defined home abbreviations'
report abbr
prefix
{write '---+ Hyperion Data Relationship Management Home Abbreviations'
 write '|*Abbreviation*|*Location*|'
}
var %hsh = getSymbols()
loop $key (keys(%hsh))
 write '|',$key,' |',$hsh{$key},' |'
if isCreated(true)
 toc '2:[[',getFile(),'][rda_report][Abbreviations]]'

=head2 config - Configuration File

Gathers F<config.xml> from F<$EPM_HOME/Master Data Management> directory.

=cut

if ?testFile('fr',catFile($EPM_HOME,'Master Data Management','config.xml'))
{var $fil = lastFile()
 debug ' Inside HDRM module, getting configuration file'
 report config
 write '---+!! Configuration File'
 write '---## Information Taken from ',encode($fil)
 call writeFile($fil)
 toc '2:[[',getFile(),'][rda_report][Configuration File]]'
}

=head2 registry - Registry Information

Collects Windows registry information.

=cut

debug ' Inside HDRM module, gathering registry information'
report registry
write '---+!! Registry Information'
write $TOC
write '---+ Install Values'
call writeRegistry(\
      'HKLM\SOFTWARE\Hyperion Solutions\Master Data Management\InstallValues')
write $TOP
write '---+ Master Data Management'
call writeRegistry('HKCU\Software\Hyperion Solutions\Master Data Management')
write $TOP
toc '2:[[',getFile(),'][rda_report][Registry Information]]'

=head1 DEPLOYMENT REPORTS

Available on version 11.1.2 and later.

=cut

if @ins = ${CUR.O_MODULE}->search('^OI')
{var $CNT = 0
 loop $itm (@ins)
 {var ($ins,$uid) = ($itm->get_first('D_HOME'),$itm->get_oid)
  call setSymbol('$EPM_INSTANCE',$ins)
  call setPrefix(concat($PRE,'i',incr($CNT)))
  toc '%SPLIT%'
  toc "1+:'",basename($ins),"' Deployment"

=head2 abbr - Abbreviations

Displays the RDA abbreviations defined for the Hyperion Data Relationship
Management instance collection.

=cut

  debug ' Inside HDRM module, collecting defined instance abbreviations'
  report abbr
  prefix
  {write '---+ Hyperion Data Relationship Management Instance Abbreviations'
   write '|*Abbreviation*|*Location*|'
  }
  var %hsh = getSymbols()
  loop $key (keys(%hsh))
   write '|',$key,' |',$hsh{$key},' |'
  if isCreated(true)
   toc '2:[[',getFile(),'][rda_report][Abbreviations]]'

=head2 Oracle WebLogic Server Information

Includes the Oracle WebLogic Server reports generated by the
L<abr:WREQ|collect::OFM:DCwreq> module for the associated Oracle WebLogic
Server domain.

=cut

  if ${CUR.O_SETUP}->search(concat('^WREQ_BI_HDRM_',replace($uid,'^OI','DOM')))
  {var ($req) = last
   var $dom = $req->get_first('I_DOMAIN')
   var $oid = $dom->get_first('I_WL_HOME')->get_oid
   var $nam = $dom->get_first('T_DOMAIN_NAME')
   toc '%PUSH("%SPLIT%")%'
   toc '%PUSH("1++:Oracle WebLogic Server Overview")%'
   toc '%INCLUDE("OFM_WREQ_BI_HDRM_',$oid,'_TF.toc",1)%'
   toc '%POP2%'
   toc '%PUSH("%SPLIT%")%'
   toc '%PUSH("1++:',"'",$nam,"'",' Domain")%'
   toc '%INCLUDE("OFM_',$req->get_oid,'_TF.toc",1)%'
   toc '%POP2%'
  }

  # Restore module prefix
  call setPrefix($PRE)
 }
}

=head1 PRODUCT REPORTS

Collects the following reports on versions earlier than 11.1.2:

=head2 Oracle WebLogic Server Information

Includes the Oracle WebLogic Server reports generated by the
L<abr:WREQ|collect::OFM:DCwreq> module for the associated Oracle WebLogic
Server domain (on versions having a product registry).

=cut

elsif ?${GRP.EPM.D_DOMAIN}
{var $dom = basename(last)
 toc '%PUSH("%SPLIT%")%'
 toc '%PUSH("1+:Oracle WebLogic Server Overview")%'
 toc '%INCLUDE("OFM_WREQ_BI_HDRM_WH_TF.toc")%'
 toc '%POP2%'
 toc '%PUSH("%SPLIT%")%'
 toc '%PUSH("1+:',"'",$dom,"'",' Domain")%'
 toc '%INCLUDE("OFM_WREQ_BI_HDRM_DOM_TF.toc")%'
 toc '%POP2%'
}

=head1 SEE ALSO

L<OFM:DCwreq|collect::OFM:DCwreq>

=head1 COPYRIGHT NOTICE

Copyright (c) 2002, 2024, Oracle and/or its affiliates. All rights reserved.

=head1 TRADEMARK NOTICE

Oracle and Java are registered trademarks of Oracle and/or its
affiliates. Other names may be trademarks of their respective owners.

=cut
