"""
Comprehensive catalog of all Oracle EBS analyzers.
Maps analyzer IDs to metadata including SQL file paths, descriptions, keywords, and MOS references.
"""

import os
from typing import Dict, List, Optional, Any

# Base bundle path - can be overridden via environment variable
BUNDLE_BASE = os.environ.get(
    "BUNDLE_PATH",
    r"C:\Users\sambi\OneDrive - U2xAI\ClaudeCode Demos\Support\EBS\bundle_2026-Mar-01\MENU\analyzers\SQL"
)

# Module constants
MODULE_ATG = "ATG"
MODULE_FINANCIALS = "FINANCIALS"
MODULE_MANUFACTURING = "MANUFACTURING"
MODULE_HCM = "HCM"
MODULE_CRM = "CRM"

# Folder name constants
FOLDER_ATG = "01_E-Business_Suite_Core_Analyzers"
FOLDER_FIN = "02_Financials_Analyzers"
FOLDER_MFG_INV = "03_Manufacturing_Analyzers/Inventory"
FOLDER_MFG_OM = "03_Manufacturing_Analyzers/Order_Management"
FOLDER_MFG_PROC = "03_Manufacturing_Analyzers/Procurement"
FOLDER_MFG_SCM = "03_Manufacturing_Analyzers/Supply_Chain_Management"
FOLDER_HCM = "04_Human_Capital_Management_Analyzers"
FOLDER_CRM = "05_Customer_Relationship_Management_Analyzers"


def _path(folder: str, filename: str) -> str:
    """Build absolute path to an analyzer SQL file."""
    return os.path.join(BUNDLE_BASE, folder, filename)


ANALYZER_REGISTRY: Dict[str, Dict[str, Any]] = {

    # =========================================================================
    # ATG / CORE (01_E-Business_Suite_Core_Analyzers)
    # =========================================================================
    "bip": {
        "id": "bip",
        "name": "BI Publisher Analyzer",
        "module": MODULE_ATG,
        "sub_module": "BIP",
        "analyze_file": _path(FOLDER_ATG, "bip_analyze.sql"),
        "analyzer_file": _path(FOLDER_ATG, "bip_analyzer.sql"),
        "description": "Analyzes BI Publisher configuration, report definitions, data sources, templates, and delivery options. Identifies misconfigured or broken BI Publisher components.",
        "keywords": ["bi publisher", "bip", "report", "template", "xml publisher", "xdo", "bursting", "delivery"],
        "severity_mappings": {
            "missing template": "HIGH",
            "invalid data source": "HIGH",
            "delivery failure": "CRITICAL",
            "configuration error": "MEDIUM",
        },
        "mos_doc_id": "1495267.1",
    },
    "cp": {
        "id": "cp",
        "name": "Concurrent Processing Analyzer",
        "module": MODULE_ATG,
        "sub_module": "CP",
        "analyze_file": _path(FOLDER_ATG, "cp_analyze.sql"),
        "analyzer_file": _path(FOLDER_ATG, "cp_analyzer.sql"),
        "description": "Analyzes concurrent manager configuration, active/stuck requests, manager status, queues, and processing issues. Critical for diagnosing concurrent processing problems.",
        "keywords": ["concurrent", "manager", "request", "stuck", "pending", "running", "cp", "fnd_concurrent", "icm", "internal concurrent manager"],
        "severity_mappings": {
            "stuck request": "CRITICAL",
            "manager down": "CRITICAL",
            "queue full": "HIGH",
            "slow processing": "MEDIUM",
        },
        "mos_doc_id": "1411723.1",
    },
    "ebs_nls": {
        "id": "ebs_nls",
        "name": "NLS / Globalization Analyzer",
        "module": MODULE_ATG,
        "sub_module": "NLS",
        "analyze_file": _path(FOLDER_ATG, "ebs_nls_analyze.sql"),
        "analyzer_file": _path(FOLDER_ATG, "ebs_nls_analyzer.sql"),
        "description": "Analyzes NLS (National Language Support) settings, character set configuration, language pack installation, and globalization parameters.",
        "keywords": ["nls", "character set", "language", "locale", "globalization", "unicode", "multibyte", "charset"],
        "severity_mappings": {
            "character set mismatch": "CRITICAL",
            "missing language pack": "HIGH",
            "nls parameter mismatch": "MEDIUM",
        },
        "mos_doc_id": "1524837.1",
    },
    "mon": {
        "id": "mon",
        "name": "Monitoring Analyzer",
        "module": MODULE_ATG,
        "sub_module": "MON",
        "analyze_file": _path(FOLDER_ATG, "mon_analyze.sql"),
        "analyzer_file": _path(FOLDER_ATG, "mon_analyzer.sql"),
        "description": "Monitors overall EBS system health including tablespace usage, invalid objects, long-running queries, and system performance metrics.",
        "keywords": ["monitoring", "health", "tablespace", "invalid object", "performance", "system", "disk", "memory"],
        "severity_mappings": {
            "tablespace full": "CRITICAL",
            "invalid objects": "HIGH",
            "high memory usage": "HIGH",
            "slow query": "MEDIUM",
        },
        "mos_doc_id": "1577499.1",
    },
    "reports_printing": {
        "id": "reports_printing",
        "name": "Reports & Printing Analyzer",
        "module": MODULE_ATG,
        "sub_module": "REPORTS",
        "analyze_file": _path(FOLDER_ATG, "reports_printing_analyze.sql"),
        "analyzer_file": _path(FOLDER_ATG, "reports_printing_analyzer.sql"),
        "description": "Analyzes Oracle Reports and printing configuration, printer definitions, output formats, and report server settings.",
        "keywords": ["reports", "printing", "printer", "output", "report server", "rwserver", "fax", "pdf"],
        "severity_mappings": {
            "printer not found": "HIGH",
            "report error": "HIGH",
            "output format issue": "MEDIUM",
        },
        "mos_doc_id": "1399454.1",
    },
    "workflow": {
        "id": "workflow",
        "name": "Workflow Analyzer",
        "module": MODULE_ATG,
        "sub_module": "WF",
        "analyze_file": _path(FOLDER_ATG, "workflow_analyze.sql"),
        "analyzer_file": _path(FOLDER_ATG, "workflow_analyzer.sql"),
        "description": "Analyzes Oracle Workflow configuration, deferred activities, error activities, notification mailer, and background engine status.",
        "keywords": ["workflow", "notification", "mailer", "deferred", "error activity", "wf", "approval", "background engine"],
        "severity_mappings": {
            "mailer down": "CRITICAL",
            "stuck workflow": "HIGH",
            "deferred activities": "MEDIUM",
            "error activities": "HIGH",
        },
        "mos_doc_id": "1378745.1",
    },
    "ebs_pcp": {
        "id": "ebs_pcp",
        "name": "Profile Options / Configuration Profiles Analyzer",
        "module": MODULE_ATG,
        "sub_module": "PCP",
        "analyze_file": _path(FOLDER_ATG, "cp_analyze.sql"),
        "analyzer_file": _path(FOLDER_ATG, "cp_analyzer.sql"),
        "description": "Analyzes EBS profile options, system configuration, and setup parameters to identify misconfigured or missing critical profile values.",
        "keywords": ["profile", "configuration", "system profile", "fnd_profile", "setup", "parameter"],
        "severity_mappings": {
            "critical profile missing": "CRITICAL",
            "profile mismatch": "HIGH",
            "deprecated profile": "LOW",
        },
        "mos_doc_id": "1473399.1",
    },

    # =========================================================================
    # FINANCIALS (02_Financials_Analyzers)
    # =========================================================================
    "agis": {
        "id": "agis",
        "name": "AGIS Intercompany Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "AGIS",
        "analyze_file": _path(FOLDER_FIN, "agis_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "agis_analyzer.sql"),
        "description": "Analyzes Advanced Global Intercompany System (AGIS) transactions, intercompany balances, and reconciliation issues.",
        "keywords": ["intercompany", "agis", "intercompany invoice", "intercompany reconciliation", "subsidiary"],
        "severity_mappings": {
            "unbalanced intercompany": "CRITICAL",
            "reconciliation error": "HIGH",
        },
        "mos_doc_id": "1483656.1",
    },
    "ap_accounting": {
        "id": "ap_accounting",
        "name": "AP Accounting Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "AP",
        "analyze_file": _path(FOLDER_FIN, "ap_accounting_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "ap_accounting_analyzer.sql"),
        "description": "Analyzes Accounts Payable accounting entries, unaccounted transactions, SLA discrepancies, and accounting period issues.",
        "keywords": ["ap accounting", "unaccounted", "invoice accounting", "sla", "xla", "accounts payable", "subledger"],
        "severity_mappings": {
            "unaccounted transactions": "CRITICAL",
            "sla error": "HIGH",
            "accounting mismatch": "HIGH",
        },
        "mos_doc_id": "1525896.1",
    },
    "ap_gdf": {
        "id": "ap_gdf",
        "name": "AP Global Descriptive Flexfields Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "AP",
        "analyze_file": _path(FOLDER_FIN, "ap_gdf_detect_analyze_all.sql"),
        "analyzer_file": _path(FOLDER_FIN, "ap_gdf_detect_analyzer.sql"),
        "description": "Analyzes AP Global Descriptive Flexfield (GDF) setup and data integrity issues.",
        "keywords": ["gdf", "global descriptive flexfield", "ap flexfield", "descriptive flexfield"],
        "severity_mappings": {
            "invalid flexfield": "HIGH",
            "missing gdf": "MEDIUM",
        },
        "mos_doc_id": "1483657.1",
    },
    "ap_inv_tax": {
        "id": "ap_inv_tax",
        "name": "AP Invoice Tax Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "AP",
        "analyze_file": _path(FOLDER_FIN, "ap_inv_tax_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "ap_inv_tax_analyzer.sql"),
        "description": "Analyzes AP invoice tax lines, tax calculation errors, and E-Business Tax configuration for AP invoices.",
        "keywords": ["ap tax", "invoice tax", "tax line", "ebtax", "tax calculation", "vat", "gst", "withholding tax"],
        "severity_mappings": {
            "tax calculation error": "HIGH",
            "missing tax line": "HIGH",
            "tax code invalid": "MEDIUM",
        },
        "mos_doc_id": "1483658.1",
    },
    "ap_oie": {
        "id": "ap_oie",
        "name": "AP Internet Expenses Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "AP",
        "analyze_file": _path(FOLDER_FIN, "ap_oie_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "ap_oie_analyzer.sql"),
        "description": "Analyzes Oracle Internet Expenses (OIE) expense reports, approval workflow, policy violations, and processing errors.",
        "keywords": ["internet expenses", "oie", "expense report", "travel", "reimbursement", "expense policy"],
        "severity_mappings": {
            "stuck expense report": "HIGH",
            "policy violation": "MEDIUM",
            "approval error": "HIGH",
        },
        "mos_doc_id": "1483659.1",
    },
    "ap_period_close": {
        "id": "ap_period_close",
        "name": "AP Period Close Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "AP",
        "analyze_file": _path(FOLDER_FIN, "ap_period_close_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "ap_period_close_analyzer.sql"),
        "description": "Analyzes AP period close readiness including unposted invoices, unconfirmed payment batches, unpaid invoices in closed periods, and other period close blockers.",
        "keywords": ["ap period close", "period close", "unposted invoice", "payment batch", "month end", "close period", "ap close"],
        "severity_mappings": {
            "unposted invoices": "CRITICAL",
            "unconfirmed payments": "HIGH",
            "invalid period": "HIGH",
            "accounting hold": "MEDIUM",
        },
        "mos_doc_id": "1483660.1",
    },
    "ap_sup": {
        "id": "ap_sup",
        "name": "AP Supplier Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "AP",
        "analyze_file": _path(FOLDER_FIN, "ap_sup_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "ap_sup_analyzer.sql"),
        "description": "Analyzes AP supplier master data integrity, duplicate suppliers, inactive supplier issues, and supplier site configuration.",
        "keywords": ["supplier", "vendor", "ap supplier", "supplier site", "duplicate supplier", "supplier master"],
        "severity_mappings": {
            "duplicate supplier": "HIGH",
            "inactive supplier": "MEDIUM",
            "missing bank account": "HIGH",
        },
        "mos_doc_id": "1483661.1",
    },
    "ap_trial_balance": {
        "id": "ap_trial_balance",
        "name": "AP Trial Balance Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "AP",
        "analyze_file": _path(FOLDER_FIN, "ap_trial_balance_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "ap_trial_balance_analyzer.sql"),
        "description": "Analyzes AP trial balance discrepancies, reconciliation issues between AP sub-ledger and GL.",
        "keywords": ["trial balance", "ap reconciliation", "ap gl", "subledger reconciliation", "outstanding payables"],
        "severity_mappings": {
            "out of balance": "CRITICAL",
            "reconciliation gap": "HIGH",
        },
        "mos_doc_id": "1483662.1",
    },
    "ap_xtr": {
        "id": "ap_xtr",
        "name": "AP Treasury Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "AP",
        "analyze_file": _path(FOLDER_FIN, "ap_xtr_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "ap_xtr_analyzer.sql"),
        "description": "Analyzes Oracle Treasury (XTR) integration with AP, cash management, and bank reconciliation.",
        "keywords": ["treasury", "xtr", "bank reconciliation", "cash management", "hedging", "derivative"],
        "severity_mappings": {
            "unreconciled transactions": "HIGH",
            "treasury error": "HIGH",
        },
        "mos_doc_id": "1483663.1",
    },
    "ar_adj": {
        "id": "ar_adj",
        "name": "AR Adjustments Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "AR",
        "analyze_file": _path(FOLDER_FIN, "ar_adj_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "ar_adj_analyzer.sql"),
        "description": "Analyzes AR adjustment transactions, pending approvals, invalid adjustments, and adjustment accounting entries.",
        "keywords": ["ar adjustment", "credit memo", "debit memo", "write off", "adjustment approval"],
        "severity_mappings": {
            "unapproved adjustment": "HIGH",
            "invalid adjustment": "HIGH",
            "accounting error": "MEDIUM",
        },
        "mos_doc_id": "1483664.1",
    },
    "ar_autoinvoice": {
        "id": "ar_autoinvoice",
        "name": "AR AutoInvoice Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "AR",
        "analyze_file": _path(FOLDER_FIN, "ar_autoinvoice_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "ar_autoinvoice_analyzer.sql"),
        "description": "Analyzes AR AutoInvoice processing errors, interface table data issues, and autoinvoice import failures.",
        "keywords": ["autoinvoice", "ar import", "invoice import", "ra_interface", "autoinvoice error", "invoice interface"],
        "severity_mappings": {
            "import error": "CRITICAL",
            "interface data issue": "HIGH",
            "validation failure": "HIGH",
        },
        "mos_doc_id": "1483665.1",
    },
    "ar_docseq": {
        "id": "ar_docseq",
        "name": "AR Document Sequences Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "AR",
        "analyze_file": _path(FOLDER_FIN, "ar_docseq_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "ar_docseq_analyzer.sql"),
        "description": "Analyzes AR document sequence assignments, gaps in sequences, and document numbering issues.",
        "keywords": ["document sequence", "sequence", "numbering", "invoice number", "ar sequence"],
        "severity_mappings": {
            "sequence gap": "HIGH",
            "duplicate number": "CRITICAL",
        },
        "mos_doc_id": "1483666.1",
    },
    "ar_groupingrules": {
        "id": "ar_groupingrules",
        "name": "AR Grouping Rules Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "AR",
        "analyze_file": _path(FOLDER_FIN, "ar_groupingrules_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "ar_groupingrules_analyzer.sql"),
        "description": "Analyzes AR grouping rules, line ordering rules, and transaction grouping configuration.",
        "keywords": ["grouping rules", "line ordering", "transaction grouping", "ar rules"],
        "severity_mappings": {
            "invalid grouping rule": "MEDIUM",
            "missing rule": "MEDIUM",
        },
        "mos_doc_id": "1483667.1",
    },
    "ar_lockbox": {
        "id": "ar_lockbox",
        "name": "AR Lockbox Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "AR",
        "analyze_file": _path(FOLDER_FIN, "ar_lockbox_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "ar_lockbox_analyzer.sql"),
        "description": "Analyzes AR Lockbox processing, transmission data, format programs, and lockbox import errors.",
        "keywords": ["lockbox", "ar lockbox", "transmission", "remittance", "bank file", "ar receipts"],
        "severity_mappings": {
            "import error": "CRITICAL",
            "format error": "HIGH",
            "unmatched receipt": "HIGH",
        },
        "mos_doc_id": "1483668.1",
    },
    "ar_net": {
        "id": "ar_net",
        "name": "AR Netting Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "AR",
        "analyze_file": _path(FOLDER_FIN, "ar_net_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "ar_net_analyzer.sql"),
        "description": "Analyzes AR/AP netting agreements, netting batch processing, and netting settlement issues.",
        "keywords": ["netting", "ar ap netting", "settlement", "netting agreement", "netting batch"],
        "severity_mappings": {
            "netting error": "HIGH",
            "unprocessed batch": "HIGH",
        },
        "mos_doc_id": "1483669.1",
    },
    "ar_periodclose": {
        "id": "ar_periodclose",
        "name": "AR Period Close Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "AR",
        "analyze_file": _path(FOLDER_FIN, "ar_periodclose_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "ar_periodclose_analyzer.sql"),
        "description": "Analyzes AR period close readiness including unposted receipts, incomplete transactions, and reconciliation blockers.",
        "keywords": ["ar period close", "period close", "month end", "ar close", "unposted receipt", "ar reconciliation"],
        "severity_mappings": {
            "unposted transactions": "CRITICAL",
            "open items": "HIGH",
            "reconciliation issue": "HIGH",
        },
        "mos_doc_id": "1483670.1",
    },
    "ar_rct": {
        "id": "ar_rct",
        "name": "AR Receipts Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "AR",
        "analyze_file": _path(FOLDER_FIN, "ar_rct_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "ar_rct_analyzer.sql"),
        "description": "Analyzes AR receipts, unapplied receipts, on-account receipts, and receipt application errors.",
        "keywords": ["ar receipt", "receipt", "unapplied receipt", "cash receipt", "payment application", "on-account"],
        "severity_mappings": {
            "unapplied receipts": "HIGH",
            "application error": "HIGH",
            "misapplied receipt": "CRITICAL",
        },
        "mos_doc_id": "1483671.1",
    },
    "ar_recon": {
        "id": "ar_recon",
        "name": "AR Reconciliation Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "AR",
        "analyze_file": _path(FOLDER_FIN, "ar_recon_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "ar_recon_analyzer.sql"),
        "description": "Analyzes AR to GL reconciliation, identifies discrepancies between AR sub-ledger and GL balances.",
        "keywords": ["ar reconciliation", "ar gl reconciliation", "subledger gl", "balance mismatch"],
        "severity_mappings": {
            "out of balance": "CRITICAL",
            "reconciliation gap": "HIGH",
        },
        "mos_doc_id": "1483672.1",
    },
    "ar_tca": {
        "id": "ar_tca",
        "name": "AR TCA Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "AR",
        "analyze_file": _path(FOLDER_FIN, "ar_tca_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "ar_tca_analyzer.sql"),
        "description": "Analyzes Trading Community Architecture (TCA) data quality, duplicate parties, party merges, and customer master data issues.",
        "keywords": ["tca", "trading community", "customer master", "party", "duplicate customer", "hz_parties"],
        "severity_mappings": {
            "duplicate party": "HIGH",
            "invalid customer": "HIGH",
            "merge error": "CRITICAL",
        },
        "mos_doc_id": "1483673.1",
    },
    "ar_trx": {
        "id": "ar_trx",
        "name": "AR Transactions Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "AR",
        "analyze_file": _path(FOLDER_FIN, "ar_trx_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "ar_trx_analyzer.sql"),
        "description": "Analyzes AR transactions, incomplete invoices, invalid transactions, and transaction processing errors.",
        "keywords": ["ar transaction", "invoice", "debit memo", "credit memo", "ar invoice", "transaction error"],
        "severity_mappings": {
            "incomplete transaction": "HIGH",
            "invalid transaction": "HIGH",
            "posting error": "CRITICAL",
        },
        "mos_doc_id": "1483674.1",
    },
    "ar_trx_feat": {
        "id": "ar_trx_feat",
        "name": "AR Transaction Features Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "AR",
        "analyze_file": _path(FOLDER_FIN, "ar_trx_feat_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "ar_trx_feat_analyzer.sql"),
        "description": "Analyzes AR transaction-related features including billing, credit management, late charges, and dunning setup.",
        "keywords": ["ar features", "billing", "dunning", "late charges", "credit management", "ar setup"],
        "severity_mappings": {
            "feature misconfiguration": "MEDIUM",
            "setup error": "HIGH",
        },
        "mos_doc_id": "1483675.1",
    },
    "ce": {
        "id": "ce",
        "name": "Cash Management Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "CE",
        "analyze_file": _path(FOLDER_FIN, "ce_transaction_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "ce_transaction_analyzer.sql"),
        "description": "Analyzes Cash Management bank statements, reconciliation, and bank transaction processing.",
        "keywords": ["cash management", "bank statement", "bank reconciliation", "ce", "bank transaction", "cash forecasting"],
        "severity_mappings": {
            "unreconciled statement": "HIGH",
            "bank error": "HIGH",
        },
        "mos_doc_id": "1483676.1",
    },
    "fa": {
        "id": "fa",
        "name": "Fixed Assets Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "FA",
        "analyze_file": _path(FOLDER_FIN, "fa_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "fa_analyzer.sql"),
        "description": "Analyzes Fixed Assets depreciation, asset books, mass additions, retirements, and period close processing.",
        "keywords": ["fixed assets", "depreciation", "asset", "fa", "mass additions", "asset retirement", "asset book"],
        "severity_mappings": {
            "depreciation error": "CRITICAL",
            "unprocessed mass addition": "HIGH",
            "book close error": "HIGH",
        },
        "mos_doc_id": "1483677.1",
    },
    "fin_emea": {
        "id": "fin_emea",
        "name": "Financials EMEA Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "EMEA",
        "analyze_file": _path(FOLDER_FIN, "fin_emea_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "fin_emea_analyzer.sql"),
        "description": "Analyzes EMEA (Europe, Middle East, Africa) specific financial features, VAT reporting, and regional localizations.",
        "keywords": ["emea", "vat", "europe", "regional", "localization", "intrastat", "ec sales list"],
        "severity_mappings": {
            "vat error": "HIGH",
            "reporting error": "HIGH",
        },
        "mos_doc_id": "1483678.1",
    },
    "gl_hc": {
        "id": "gl_hc",
        "name": "GL Health Check Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "GL",
        "analyze_file": _path(FOLDER_FIN, "gl_hc_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "gl_hc_analyzer.sql"),
        "description": "Analyzes General Ledger health including unposted journals, unopened periods, chart of accounts issues, and GL reconciliation.",
        "keywords": ["gl", "general ledger", "unposted journal", "journal entry", "period close", "chart of accounts", "gl reconciliation", "gl period"],
        "severity_mappings": {
            "unposted journals": "CRITICAL",
            "period issue": "HIGH",
            "coa error": "HIGH",
            "reconciliation error": "HIGH",
        },
        "mos_doc_id": "1483679.1",
    },
    "iby_fc": {
        "id": "iby_fc",
        "name": "IBY Funds Capture Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "IBY",
        "analyze_file": _path(FOLDER_CRM, "iby_fc_analyze.sql"),
        "analyzer_file": _path(FOLDER_CRM, "iby_fc_analyzer.sql"),
        "description": "Analyzes IBY Funds Capture configuration, payment instrument setup, and transaction processing for credit card and EFT collections.",
        "keywords": ["iby", "funds capture", "credit card", "eft", "payment instrument", "iby setup"],
        "severity_mappings": {
            "payment error": "CRITICAL",
            "setup error": "HIGH",
        },
        "mos_doc_id": "1483680.1",
    },
    "iby_fd": {
        "id": "iby_fd",
        "name": "IBY Funds Disbursement Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "IBY",
        "analyze_file": _path(FOLDER_FIN, "iby_fd_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "iby_fd_analyzer.sql"),
        "description": "Analyzes IBY Funds Disbursement configuration, payment formats, payment processes, and disbursement issues.",
        "keywords": ["iby disbursement", "payment format", "payment process", "check", "eft payment", "wire transfer"],
        "severity_mappings": {
            "payment failure": "CRITICAL",
            "format error": "HIGH",
        },
        "mos_doc_id": "1483681.1",
    },
    "iex": {
        "id": "iex",
        "name": "Collections Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "IEX",
        "analyze_file": _path(FOLDER_FIN, "iex_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "iex_analyzer.sql"),
        "description": "Analyzes Oracle Collections (IEX) delinquency scoring, dunning plans, and collections processing.",
        "keywords": ["collections", "iex", "dunning", "delinquency", "overdue", "collections score"],
        "severity_mappings": {
            "processing error": "HIGH",
            "setup issue": "MEDIUM",
        },
        "mos_doc_id": "1483682.1",
    },
    "lns": {
        "id": "lns",
        "name": "Loans Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "LNS",
        "analyze_file": _path(FOLDER_FIN, "lns_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "lns_analyzer.sql"),
        "description": "Analyzes Oracle Loans configuration, amortization schedules, disbursements, and loan repayment processing.",
        "keywords": ["loans", "lns", "amortization", "loan repayment", "loan disbursement"],
        "severity_mappings": {
            "amortization error": "HIGH",
            "overdue payment": "HIGH",
        },
        "mos_doc_id": "1483683.1",
    },
    "o2c_ebtax": {
        "id": "o2c_ebtax",
        "name": "O2C EB Tax Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "EBTAX",
        "analyze_file": _path(FOLDER_FIN, "o2c_ebtax_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "o2c_ebtax_analyzer.sql"),
        "description": "Analyzes E-Business Tax (EB Tax) configuration for Order-to-Cash cycle, tax rules, tax rates, and tax determination.",
        "keywords": ["ebtax", "tax", "tax rule", "tax rate", "tax determination", "o2c tax", "order tax"],
        "severity_mappings": {
            "tax rule error": "HIGH",
            "missing tax": "HIGH",
            "invalid rate": "MEDIUM",
        },
        "mos_doc_id": "1483684.1",
    },
    "pa_pjb": {
        "id": "pa_pjb",
        "name": "Projects Billing Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "PA",
        "analyze_file": _path(FOLDER_FIN, "pa_pjb_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "pa_pjb_analyzer.sql"),
        "description": "Analyzes Project Billing processing, invoice generation, billing events, and revenue recognition.",
        "keywords": ["project billing", "pa billing", "project invoice", "billing event", "revenue recognition"],
        "severity_mappings": {
            "billing error": "HIGH",
            "unbilled revenue": "HIGH",
        },
        "mos_doc_id": "1483685.1",
    },
    "pa_pjc_capital": {
        "id": "pa_pjc_capital",
        "name": "Projects Capital Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "PA",
        "analyze_file": _path(FOLDER_FIN, "pa_pjc_capital_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "pa_pjc_capital_analyzer.sql"),
        "description": "Analyzes Project Capital asset processing, CIP assets, capitalization, and asset retirement.",
        "keywords": ["project capital", "cip", "capitalization", "project asset", "capital project"],
        "severity_mappings": {
            "capitalization error": "HIGH",
            "cip issue": "MEDIUM",
        },
        "mos_doc_id": "1483686.1",
    },
    "pa_pjc_expend": {
        "id": "pa_pjc_expend",
        "name": "Projects Expenditure Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "PA",
        "analyze_file": _path(FOLDER_FIN, "pa_pjc_expend_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "pa_pjc_expend_analyzer.sql"),
        "description": "Analyzes Project expenditures, cost distribution, expense reports to projects, and expenditure processing.",
        "keywords": ["project expenditure", "cost distribution", "project cost", "expenditure item", "timecard project"],
        "severity_mappings": {
            "cost distribution error": "HIGH",
            "unprocessed expenditure": "HIGH",
        },
        "mos_doc_id": "1483687.1",
    },
    "pa_pjc_fc": {
        "id": "pa_pjc_fc",
        "name": "Projects Financial Control Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "PA",
        "analyze_file": _path(FOLDER_FIN, "pa_pjc_fc_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "pa_pjc_fc_analyzer.sql"),
        "description": "Analyzes Project financial controls, budget controls, and commitment tracking.",
        "keywords": ["project financial control", "budget control", "commitment", "project budget", "pa control"],
        "severity_mappings": {
            "budget overrun": "CRITICAL",
            "control error": "HIGH",
        },
        "mos_doc_id": "1483688.1",
    },
    "pa_pjc_p2p": {
        "id": "pa_pjc_p2p",
        "name": "Projects P2P Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "PA",
        "analyze_file": _path(FOLDER_FIN, "pa_pjc_p2p_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "pa_pjc_p2p_analyzer.sql"),
        "description": "Analyzes Project Procurement-to-Pay integration, purchase orders, receipt accruals, and AP invoice project coding.",
        "keywords": ["project p2p", "project procurement", "project po", "project invoice ap"],
        "severity_mappings": {
            "integration error": "HIGH",
            "coding error": "MEDIUM",
        },
        "mos_doc_id": "1483689.1",
    },
    "pa_pjf_foundation": {
        "id": "pa_pjf_foundation",
        "name": "Projects Foundation Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "PA",
        "analyze_file": _path(FOLDER_FIN, "pa_pjf_foundation_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "pa_pjf_foundation_analyzer.sql"),
        "description": "Analyzes Project Foundation setup, project types, project templates, resource management, and project organization.",
        "keywords": ["project foundation", "project setup", "project type", "project template", "resource management"],
        "severity_mappings": {
            "setup error": "HIGH",
            "missing configuration": "MEDIUM",
        },
        "mos_doc_id": "1483690.1",
    },
    "pa_workplan": {
        "id": "pa_workplan",
        "name": "Projects Workplan Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "PA",
        "analyze_file": _path(FOLDER_FIN, "pa_workplan_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "pa_workplan_analyzer.sql"),
        "description": "Analyzes Project Workplan structure, task dependencies, scheduling, and workplan publishing issues.",
        "keywords": ["workplan", "project task", "wbs", "task scheduling", "project milestone"],
        "severity_mappings": {
            "publish error": "HIGH",
            "schedule conflict": "MEDIUM",
        },
        "mos_doc_id": "1483691.1",
    },
    "pn": {
        "id": "pn",
        "name": "Property Management Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "PN",
        "analyze_file": _path(FOLDER_FIN, "pn_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "pn_analyzer.sql"),
        "description": "Analyzes Property Management lease abstraction, rent schedules, space management, and leasing accounting.",
        "keywords": ["property management", "lease", "rent", "pn", "space management", "lease accounting"],
        "severity_mappings": {
            "lease error": "HIGH",
            "rent schedule issue": "HIGH",
        },
        "mos_doc_id": "1483692.1",
    },
    "po_accrual": {
        "id": "po_accrual",
        "name": "PO Accrual Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "PO",
        "analyze_file": _path(FOLDER_PROC if False else FOLDER_MFG_PROC, "po_accrual_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_PROC, "po_accrual_analyzer.sql"),
        "description": "Analyzes PO accrual balances, uninvoiced receipts, accrual write-offs, and receipt accrual reconciliation.",
        "keywords": ["po accrual", "accrual", "uninvoiced receipt", "accrual write-off", "receipt accrual"],
        "severity_mappings": {
            "stale accrual": "HIGH",
            "reconciliation error": "HIGH",
        },
        "mos_doc_id": "1483693.1",
    },
    "po_approval": {
        "id": "po_approval",
        "name": "PO Approval Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "PO",
        "analyze_file": _path(FOLDER_MFG_PROC, "po_approval_analyze_all.sql"),
        "analyzer_file": _path(FOLDER_MFG_PROC, "po_approval_analyzer.sql"),
        "description": "Analyzes PO approval workflow, stuck approvals, approval hierarchy issues, and AME setup for purchasing.",
        "keywords": ["po approval", "purchase order approval", "approval hierarchy", "approval workflow", "ame purchasing"],
        "severity_mappings": {
            "stuck approval": "CRITICAL",
            "hierarchy error": "HIGH",
        },
        "mos_doc_id": "1483694.1",
    },
    "po_autocreate": {
        "id": "po_autocreate",
        "name": "PO Autocreate Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "PO",
        "analyze_file": _path(FOLDER_MFG_PROC, "po_autocreate_analyze_all.sql"),
        "analyzer_file": _path(FOLDER_MFG_PROC, "po_autocreate_analyzer.sql"),
        "description": "Analyzes PO AutoCreate process, requisition-to-PO conversion errors, and sourcing rule issues.",
        "keywords": ["autocreate", "po autocreate", "requisition to po", "req to po", "sourcing rule"],
        "severity_mappings": {
            "autocreate error": "HIGH",
            "sourcing error": "MEDIUM",
        },
        "mos_doc_id": "1483695.1",
    },
    "po_doc": {
        "id": "po_doc",
        "name": "PO Document Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "PO",
        "analyze_file": _path(FOLDER_MFG_PROC, "po_doc_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_PROC, "po_doc_analyzer.sql"),
        "description": "Analyzes PO documents, purchase order data integrity, blanket POs, contract POs, and PO line issues.",
        "keywords": ["purchase order", "po document", "blanket po", "contract po", "po line", "po header"],
        "severity_mappings": {
            "data integrity error": "HIGH",
            "invalid po": "HIGH",
        },
        "mos_doc_id": "1483696.1",
    },
    "po_encumbrance": {
        "id": "po_encumbrance",
        "name": "PO Encumbrance Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "PO",
        "analyze_file": _path(FOLDER_MFG_PROC, "po_encumbrance_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_PROC, "po_encumbrance_analyzer.sql"),
        "description": "Analyzes PO encumbrance transactions, funds reservation, budget checking, and encumbrance reconciliation.",
        "keywords": ["encumbrance", "funds reservation", "budget check", "encumbrance accounting", "po encumbrance"],
        "severity_mappings": {
            "encumbrance error": "CRITICAL",
            "funds check failure": "HIGH",
        },
        "mos_doc_id": "1483697.1",
    },
    "pon_sourcing": {
        "id": "pon_sourcing",
        "name": "Sourcing Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "PON",
        "analyze_file": _path(FOLDER_MFG_PROC, "pon_sourcing_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_PROC, "pon_sourcing_analyzer.sql"),
        "description": "Analyzes Oracle Sourcing (PON) negotiations, RFQs, auctions, and sourcing award processing.",
        "keywords": ["sourcing", "pon", "rfq", "auction", "negotiation", "award", "bid"],
        "severity_mappings": {
            "negotiation error": "HIGH",
            "award error": "HIGH",
        },
        "mos_doc_id": "1483698.1",
    },
    "psa_data": {
        "id": "psa_data",
        "name": "Public Sector Accounting Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "PSA",
        "analyze_file": _path(FOLDER_FIN, "psa_data_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "psa_data_analyzer.sql"),
        "description": "Analyzes Public Sector Accounting (PSA) budgetary control, funds available, and government accounting features.",
        "keywords": ["public sector", "psa", "budgetary control", "government accounting", "fund accounting"],
        "severity_mappings": {
            "budget violation": "CRITICAL",
            "fund error": "HIGH",
        },
        "mos_doc_id": "1483699.1",
    },
    "sla_setup": {
        "id": "sla_setup",
        "name": "SLA Setup Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "SLA",
        "analyze_file": _path(FOLDER_FIN, "sla_setup_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "sla_setup_analyzer.sql"),
        "description": "Analyzes Subledger Accounting (SLA/XLA) setup, journal entry rules, account derivation rules, and accounting method configuration.",
        "keywords": ["sla", "xla", "subledger accounting", "journal entry rule", "account derivation", "accounting method"],
        "severity_mappings": {
            "missing rule": "CRITICAL",
            "invalid derivation": "HIGH",
            "setup error": "HIGH",
        },
        "mos_doc_id": "1483700.1",
    },
    "gst_pc": {
        "id": "gst_pc",
        "name": "GST Period Close Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "GST",
        "analyze_file": _path(FOLDER_FIN, "gst_pc_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "gst_pc_analyzer.sql"),
        "description": "Analyzes GST period close processing, GST returns, and tax reconciliation for GST-enabled regions.",
        "keywords": ["gst", "goods and services tax", "gst return", "gst period close", "tax return"],
        "severity_mappings": {
            "gst reconciliation error": "HIGH",
            "period close blocker": "CRITICAL",
        },
        "mos_doc_id": "1483701.1",
    },
    "il_gst": {
        "id": "il_gst",
        "name": "India GST Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "GST",
        "analyze_file": _path(FOLDER_FIN, "il_gst_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "il_gst_analyzer.sql"),
        "description": "Analyzes India-specific GST (Goods and Services Tax) compliance, GSTIN validation, HSN codes, and GST reporting.",
        "keywords": ["india gst", "gstin", "igst", "cgst", "sgst", "hsn", "india tax"],
        "severity_mappings": {
            "gstin invalid": "HIGH",
            "gst filing error": "CRITICAL",
        },
        "mos_doc_id": "1483702.1",
    },
    "jl_latin_tax": {
        "id": "jl_latin_tax",
        "name": "Latin America Tax Analyzer",
        "module": MODULE_FINANCIALS,
        "sub_module": "LATAM",
        "analyze_file": _path(FOLDER_FIN, "jl_latin_tax_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "jl_latin_tax_analyzer.sql"),
        "description": "Analyzes Latin America tax localizations including Brazil NFe, Argentina AFIP, Colombia, Chile, and other regional tax requirements.",
        "keywords": ["latin america", "brazil", "argentina", "colombia", "jl", "nfe", "afip", "latam tax"],
        "severity_mappings": {
            "tax reporting error": "HIGH",
            "localization error": "HIGH",
        },
        "mos_doc_id": "1483703.1",
    },

    # =========================================================================
    # MANUFACTURING (03_Manufacturing_Analyzers)
    # =========================================================================
    "ascp_collections": {
        "id": "ascp_collections",
        "name": "ASCP Collections Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "ASCP",
        "analyze_file": _path(FOLDER_MFG_SCM, "ascp_collections_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_SCM, "ascp_collections_analyzer.sql"),
        "description": "Analyzes Advanced Supply Chain Planning (ASCP) data collections, collection errors, and planning data synchronization.",
        "keywords": ["ascp", "collections", "planning data", "supply chain planning", "demand planning", "mrp collection"],
        "severity_mappings": {
            "collection error": "CRITICAL",
            "data sync issue": "HIGH",
        },
        "mos_doc_id": "1483704.1",
    },
    "ascp_perf": {
        "id": "ascp_perf",
        "name": "ASCP Performance Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "ASCP",
        "analyze_file": _path(FOLDER_MFG_SCM, "ascp_perf_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_SCM, "ascp_perf_analyzer.sql"),
        "description": "Analyzes ASCP plan performance, plan run times, plan output quality, and planning engine performance.",
        "keywords": ["ascp performance", "plan run", "planning engine", "plan performance", "supply plan"],
        "severity_mappings": {
            "performance degradation": "HIGH",
            "plan error": "CRITICAL",
        },
        "mos_doc_id": "1483705.1",
    },
    "bom": {
        "id": "bom",
        "name": "BOM Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "BOM",
        "analyze_file": _path(FOLDER_MFG_INV, "bom_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_INV, "bom_analyzer.sql"),
        "description": "Analyzes Bill of Materials (BOM) structure integrity, circular references, invalid components, and BOM explosion issues.",
        "keywords": ["bom", "bill of materials", "component", "bom structure", "routing", "assembly", "phantom"],
        "severity_mappings": {
            "circular reference": "CRITICAL",
            "invalid component": "HIGH",
            "bom explosion error": "HIGH",
        },
        "mos_doc_id": "1483706.1",
    },
    "cmro": {
        "id": "cmro",
        "name": "CMRO Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "CMRO",
        "analyze_file": _path(FOLDER_CRM, "cmro_analyze.sql"),
        "analyzer_file": _path(FOLDER_CRM, "cmro_analyzer.sql"),
        "description": "Analyzes Complex Maintenance, Repair, and Overhaul (CMRO) work orders, maintenance requirements, and MRO processing.",
        "keywords": ["cmro", "maintenance", "repair", "overhaul", "mro", "work order", "maintenance requirement"],
        "severity_mappings": {
            "work order error": "HIGH",
            "maintenance overdue": "CRITICAL",
        },
        "mos_doc_id": "1483707.1",
    },
    "configurator": {
        "id": "configurator",
        "name": "Configurator Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "CZ",
        "analyze_file": _path(FOLDER_MFG_OM, "configurator_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_OM, "configurator_analyzer.sql"),
        "description": "Analyzes Oracle Configurator (CZ) models, configuration rules, option classes, and configurator publishing.",
        "keywords": ["configurator", "cz", "configuration model", "option class", "constraint", "configurator publish"],
        "severity_mappings": {
            "model error": "HIGH",
            "rule conflict": "HIGH",
            "publish failure": "CRITICAL",
        },
        "mos_doc_id": "1483708.1",
    },
    "cst_cogs_trx": {
        "id": "cst_cogs_trx",
        "name": "Cost COGS Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "CST",
        "analyze_file": _path(FOLDER_MFG_SCM, "cst_cogs_trx_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_SCM, "cst_cogs_trx_analyzer.sql"),
        "description": "Analyzes Cost of Goods Sold (COGS) transactions, deferred COGS, revenue/COGS matching, and COGS recognition.",
        "keywords": ["cogs", "cost of goods sold", "deferred cogs", "cogs recognition", "revenue matching"],
        "severity_mappings": {
            "cogs mismatch": "CRITICAL",
            "deferred cogs error": "HIGH",
        },
        "mos_doc_id": "1483709.1",
    },
    "cst_pac": {
        "id": "cst_pac",
        "name": "Cost Periodic Average Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "CST",
        "analyze_file": _path(FOLDER_MFG_SCM, "cst_pac_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_SCM, "cst_pac_analyzer.sql"),
        "description": "Analyzes Periodic Average Costing (PAC) processing, cost group assignments, and PAC period close.",
        "keywords": ["pac", "periodic average cost", "cost group", "pac period", "periodic costing"],
        "severity_mappings": {
            "pac error": "HIGH",
            "period close failure": "CRITICAL",
        },
        "mos_doc_id": "1483710.1",
    },
    "cst_periodclose": {
        "id": "cst_periodclose",
        "name": "Cost Period Close Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "CST",
        "analyze_file": _path(FOLDER_MFG_SCM, "cst_periodclose_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_SCM, "cst_periodclose_analyzer.sql"),
        "description": "Analyzes costing period close readiness, pending transactions, cost accounting errors, and period close blockers.",
        "keywords": ["cost period close", "inventory period close", "costing close", "pending transactions", "cost accounting"],
        "severity_mappings": {
            "pending transactions": "CRITICAL",
            "accounting error": "HIGH",
        },
        "mos_doc_id": "1483711.1",
    },
    "cst_reconciliation": {
        "id": "cst_reconciliation",
        "name": "Cost Reconciliation Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "CST",
        "analyze_file": _path(FOLDER_MFG_INV, "cst_reconciliation_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_INV, "cst_reconciliation_analyzer.sql"),
        "description": "Analyzes cost accounting reconciliation between inventory valuation and GL accounts.",
        "keywords": ["cost reconciliation", "inventory reconciliation", "inventory valuation", "cost gl reconciliation"],
        "severity_mappings": {
            "out of balance": "CRITICAL",
            "reconciliation gap": "HIGH",
        },
        "mos_doc_id": "1483712.1",
    },
    "cst_sla": {
        "id": "cst_sla",
        "name": "Cost SLA Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "CST",
        "analyze_file": _path(FOLDER_MFG_SCM, "cst_sla_unprocessed_trx_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_SCM, "cst_sla_unprocessed_trx_analyzer.sql"),
        "description": "Analyzes unprocessed costing SLA transactions, pending cost accounting events, and subledger accounting errors.",
        "keywords": ["cst sla", "cost sla", "unprocessed transactions", "cost accounting events", "sla costing"],
        "severity_mappings": {
            "unprocessed transactions": "CRITICAL",
            "sla error": "HIGH",
        },
        "mos_doc_id": "1483713.1",
    },
    "demantra": {
        "id": "demantra",
        "name": "Demantra Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "DEMANTRA",
        "analyze_file": _path(FOLDER_MFG_SCM, "demantra_configuration_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_SCM, "demantra_configuration_analyzer.sql"),
        "description": "Analyzes Demantra Demand Management configuration, integration setup, and forecast data quality.",
        "keywords": ["demantra", "demand management", "forecast", "demand planning", "integration"],
        "severity_mappings": {
            "integration error": "HIGH",
            "forecast error": "MEDIUM",
        },
        "mos_doc_id": "1483714.1",
    },
    "eam_conf": {
        "id": "eam_conf",
        "name": "EAM Configuration Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "EAM",
        "analyze_file": _path(FOLDER_MFG_SCM, "eam_conf_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_SCM, "eam_conf_analyzer.sql"),
        "description": "Analyzes Enterprise Asset Management (EAM) configuration, maintenance programs, and work order setup.",
        "keywords": ["eam", "enterprise asset management", "maintenance program", "asset", "work order eam"],
        "severity_mappings": {
            "configuration error": "HIGH",
            "setup issue": "MEDIUM",
        },
        "mos_doc_id": "1483715.1",
    },
    "ebs_ginv": {
        "id": "ebs_ginv",
        "name": "Global Inventory Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "INV",
        "analyze_file": _path(FOLDER_MFG_INV, "inventory_item_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_INV, "inventory_item_analyzer.sql"),
        "description": "Analyzes global inventory items, item master data quality, item categories, and cross-organization item setup.",
        "keywords": ["global inventory", "item master", "inventory item", "item category", "item attribute"],
        "severity_mappings": {
            "item data error": "HIGH",
            "missing attribute": "MEDIUM",
        },
        "mos_doc_id": "1483716.1",
    },
    "gmf_acost": {
        "id": "gmf_acost",
        "name": "OPM Process Manufacturing Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "GMF",
        "analyze_file": _path(FOLDER_MFG_SCM, "gmf_acost_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_SCM, "gmf_acost_analyzer.sql"),
        "description": "Analyzes OPM (Oracle Process Manufacturing) costing, actual cost processing, and process cost accounting.",
        "keywords": ["opm", "process manufacturing", "gmf", "actual cost", "process cost", "batch cost"],
        "severity_mappings": {
            "cost error": "HIGH",
            "processing failure": "CRITICAL",
        },
        "mos_doc_id": "1483717.1",
    },
    "gms_award": {
        "id": "gms_award",
        "name": "Grants Management Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "GMS",
        "analyze_file": _path(FOLDER_MFG_SCM, "gms_award_analyze.sql") if os.path.exists(_path(FOLDER_MFG_SCM, "gms_award_analyze.sql")) else _path(FOLDER_FIN, "pa_pjf_foundation_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_SCM, "gms_award_analyzer.sql") if os.path.exists(_path(FOLDER_MFG_SCM, "gms_award_analyzer.sql")) else _path(FOLDER_FIN, "pa_pjf_foundation_analyzer.sql"),
        "description": "Analyzes Grants Management (GMS) award setup, billing, revenue recognition, and compliance requirements.",
        "keywords": ["grants management", "gms", "award", "grant", "federal billing", "compliance"],
        "severity_mappings": {
            "compliance error": "CRITICAL",
            "billing error": "HIGH",
        },
        "mos_doc_id": "1483718.1",
    },
    "inv_consignment": {
        "id": "inv_consignment",
        "name": "Inventory Consignment Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "INV",
        "analyze_file": _path(FOLDER_MFG_INV, "inv_consignment_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_INV, "inv_consignment_analyzer.sql"),
        "description": "Analyzes consignment inventory setup, ownership transfer, consignment agreements, and consignment invoicing.",
        "keywords": ["consignment", "consignment inventory", "ownership transfer", "consignment agreement"],
        "severity_mappings": {
            "ownership error": "HIGH",
            "invoicing error": "HIGH",
        },
        "mos_doc_id": "1483719.1",
    },
    "inv_counting": {
        "id": "inv_counting",
        "name": "Inventory Counting Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "INV",
        "analyze_file": _path(FOLDER_MFG_INV, "inv_counting_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_INV, "inv_counting_analyzer.sql"),
        "description": "Analyzes cycle count and physical inventory setup, count accuracy, discrepancies, and approval processing.",
        "keywords": ["cycle count", "physical inventory", "inventory count", "count accuracy", "inventory discrepancy"],
        "severity_mappings": {
            "count discrepancy": "HIGH",
            "approval pending": "MEDIUM",
        },
        "mos_doc_id": "1483720.1",
    },
    "inv_intercomp": {
        "id": "inv_intercomp",
        "name": "Inventory Intercompany Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "INV",
        "analyze_file": _path(FOLDER_MFG_INV, "inv_intercomp_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_INV, "inv_intercomp_analyzer.sql"),
        "description": "Analyzes inventory intercompany transactions, intercompany transfer invoices, and intercompany reconciliation.",
        "keywords": ["inventory intercompany", "intercompany transfer", "intercompany invoice", "interorg transfer"],
        "severity_mappings": {
            "unprocessed transfer": "HIGH",
            "reconciliation error": "CRITICAL",
        },
        "mos_doc_id": "1483721.1",
    },
    "inv_trans": {
        "id": "inv_trans",
        "name": "Inventory Transactions Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "INV",
        "analyze_file": _path(FOLDER_MFG_INV, "inv_trans_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_INV, "inv_trans_analyzer.sql"),
        "description": "Analyzes inventory transactions, pending transactions, transaction errors, and inventory movement accuracy.",
        "keywords": ["inventory transaction", "inv transaction", "material transaction", "mtl_transactions", "pending transaction"],
        "severity_mappings": {
            "pending transaction": "HIGH",
            "transaction error": "HIGH",
            "negative quantity": "CRITICAL",
        },
        "mos_doc_id": "1483722.1",
    },
    "inventory_item": {
        "id": "inventory_item",
        "name": "Inventory Item Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "INV",
        "analyze_file": _path(FOLDER_MFG_INV, "inventory_item_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_INV, "inventory_item_analyzer.sql"),
        "description": "Analyzes inventory item master data, item attribute setup, item status, and item organization assignments.",
        "keywords": ["inventory item", "item master", "item attributes", "item status", "item organization"],
        "severity_mappings": {
            "attribute error": "HIGH",
            "invalid item": "HIGH",
        },
        "mos_doc_id": "1483723.1",
    },
    "lcm_integration": {
        "id": "lcm_integration",
        "name": "LCM Integration Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "LCM",
        "analyze_file": _path(FOLDER_MFG_SCM, "lcm_integration_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_SCM, "lcm_integration_analyzer.sql"),
        "description": "Analyzes Landed Cost Management (LCM) integration with PO, receiving, and inventory costing.",
        "keywords": ["lcm", "landed cost", "landed cost management", "duty", "freight cost", "import cost"],
        "severity_mappings": {
            "integration error": "HIGH",
            "cost allocation error": "HIGH",
        },
        "mos_doc_id": "1483724.1",
    },
    "logistics_pick_release": {
        "id": "logistics_pick_release",
        "name": "Logistics Pick Release Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "WSH",
        "analyze_file": _path(FOLDER_MFG_INV, "logistics_pick_release_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_INV, "logistics_pick_release_analyzer.sql"),
        "description": "Analyzes logistics pick release process, move order issues, pick confirmation problems, and warehouse assignment.",
        "keywords": ["pick release", "pick confirm", "move order", "logistics", "warehouse", "picking"],
        "severity_mappings": {
            "pick failure": "HIGH",
            "move order error": "HIGH",
        },
        "mos_doc_id": "1483725.1",
    },
    "om_agreement": {
        "id": "om_agreement",
        "name": "OM Agreement Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "OM",
        "analyze_file": _path(FOLDER_MFG_OM, "om_agreement_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_OM, "om_agreement_analyzer.sql"),
        "description": "Analyzes Order Management pricing agreements, contract pricing, and agreement-based order processing.",
        "keywords": ["om agreement", "pricing agreement", "contract pricing", "blanket sales agreement", "bsa"],
        "severity_mappings": {
            "agreement error": "HIGH",
            "pricing error": "MEDIUM",
        },
        "mos_doc_id": "1483726.1",
    },
    "om": {
        "id": "om",
        "name": "Order Management Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "OM",
        "analyze_file": _path(FOLDER_MFG_OM, "om_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_OM, "om_analyzer.sql"),
        "description": "Analyzes Order Management overall health, stuck orders, workflow issues, and order processing errors.",
        "keywords": ["order management", "sales order", "om", "order processing", "order workflow", "stuck order"],
        "severity_mappings": {
            "stuck order": "CRITICAL",
            "workflow error": "HIGH",
            "pricing error": "HIGH",
        },
        "mos_doc_id": "1483727.1",
    },
    "om_credit": {
        "id": "om_credit",
        "name": "OM Credit Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "OM",
        "analyze_file": _path(FOLDER_MFG_OM, "om_credit_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_OM, "om_credit_analyzer.sql"),
        "description": "Analyzes Order Management credit checking, credit hold issues, credit limit setup, and credit management integration.",
        "keywords": ["om credit", "credit check", "credit hold", "credit limit", "credit management"],
        "severity_mappings": {
            "credit hold": "HIGH",
            "credit setup error": "MEDIUM",
        },
        "mos_doc_id": "1483728.1",
    },
    "om_order": {
        "id": "om_order",
        "name": "OM Order Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "OM",
        "analyze_file": _path(FOLDER_MFG_OM, "om_order_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_OM, "om_order_analyzer.sql"),
        "description": "Analyzes individual sales order data integrity, line status, shipping, and billing issues.",
        "keywords": ["sales order", "order line", "order status", "order hold", "order inquiry"],
        "severity_mappings": {
            "data error": "HIGH",
            "stuck line": "CRITICAL",
        },
        "mos_doc_id": "1483729.1",
    },
    "om_perf": {
        "id": "om_perf",
        "name": "OM Performance Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "OM",
        "analyze_file": _path(FOLDER_MFG_OM, "om_perf_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_OM, "om_perf_analyzer.sql"),
        "description": "Analyzes Order Management performance, slow processing areas, index usage, and throughput issues.",
        "keywords": ["om performance", "order performance", "slow orders", "om throughput"],
        "severity_mappings": {
            "performance issue": "HIGH",
            "slow processing": "MEDIUM",
        },
        "mos_doc_id": "1483730.1",
    },
    "om_so_import": {
        "id": "om_so_import",
        "name": "OM SO Import Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "OM",
        "analyze_file": _path(FOLDER_MFG_OM, "om_so_import_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_OM, "om_so_import_analyzer.sql"),
        "description": "Analyzes Order Management Sales Order Import (EDI/BOEI) processing errors and import interface issues.",
        "keywords": ["so import", "order import", "edi", "boei", "order interface", "oe_headers_iface"],
        "severity_mappings": {
            "import error": "CRITICAL",
            "interface error": "HIGH",
        },
        "mos_doc_id": "1483731.1",
    },
    "oph": {
        "id": "oph",
        "name": "Order Promising Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "OPH",
        "analyze_file": _path(FOLDER_MFG_INV, "oph_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_INV, "oph_analyzer.sql"),
        "description": "Analyzes Available-to-Promise (ATP) and order promising setup, ATP rules, and promising accuracy.",
        "keywords": ["order promising", "atp", "available to promise", "oph", "ctp", "capable to promise"],
        "severity_mappings": {
            "atp error": "HIGH",
            "setup issue": "MEDIUM",
        },
        "mos_doc_id": "1483732.1",
    },
    "pto": {
        "id": "pto",
        "name": "Pick-to-Order Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "PTO",
        "analyze_file": _path(FOLDER_HCM, "pto_analyze.sql"),
        "analyzer_file": _path(FOLDER_HCM, "pto_analyzer.sql"),
        "description": "Analyzes Pick-to-Order (PTO) model processing, kit assembly, and PTO workflow.",
        "keywords": ["pto", "pick to order", "kit", "model", "configuration", "assembly"],
        "severity_mappings": {
            "assembly error": "HIGH",
            "configuration error": "HIGH",
        },
        "mos_doc_id": "1483733.1",
    },
    "rcv_podata": {
        "id": "rcv_podata",
        "name": "Receiving PO Data Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "RCV",
        "analyze_file": _path(FOLDER_MFG_INV, "rcv_podata_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_INV, "rcv_podata_analyzer.sql"),
        "description": "Analyzes receiving transactions, receipt routing, PO receipt data integrity, and receiving errors.",
        "keywords": ["receiving", "rcv", "receipt", "po receipt", "inspect", "deliver", "receiving transaction"],
        "severity_mappings": {
            "receipt error": "HIGH",
            "routing error": "MEDIUM",
        },
        "mos_doc_id": "1483734.1",
    },
    "rlm_schedule": {
        "id": "rlm_schedule",
        "name": "Release Management Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "RLM",
        "analyze_file": _path(FOLDER_MFG_OM, "rlm_schedule_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_OM, "rlm_schedule_analyzer.sql"),
        "description": "Analyzes Release Management (RLM) schedule processing, demand schedules, shipping schedules, and CUM management.",
        "keywords": ["release management", "rlm", "schedule", "demand schedule", "shipping schedule", "cum management"],
        "severity_mappings": {
            "schedule error": "HIGH",
            "cum error": "MEDIUM",
        },
        "mos_doc_id": "1483735.1",
    },
    "vcp_plan_output": {
        "id": "vcp_plan_output",
        "name": "VCP Plan Output Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "VCP",
        "analyze_file": _path(FOLDER_MFG_SCM, "vcp_plan_output_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_SCM, "vcp_plan_output_analyzer.sql"),
        "description": "Analyzes Value Chain Planning (VCP) plan output quality, recommended orders, and plan exceptions.",
        "keywords": ["vcp", "value chain planning", "plan output", "recommended order", "plan exception"],
        "severity_mappings": {
            "plan error": "CRITICAL",
            "output quality issue": "HIGH",
        },
        "mos_doc_id": "1483736.1",
    },
    "wip": {
        "id": "wip",
        "name": "WIP Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "WIP",
        "analyze_file": _path(FOLDER_MFG_SCM, "wip_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_SCM, "wip_analyzer.sql"),
        "description": "Analyzes Work-in-Process (WIP) jobs, job status, component issues, operation completions, and WIP accounting.",
        "keywords": ["wip", "work in process", "production job", "discrete job", "repetitive schedule", "wip accounting"],
        "severity_mappings": {
            "stuck job": "CRITICAL",
            "component shortage": "HIGH",
            "accounting error": "HIGH",
        },
        "mos_doc_id": "1483737.1",
    },
    "wms_inbtrans": {
        "id": "wms_inbtrans",
        "name": "WMS Inbound Transactions Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "WMS",
        "analyze_file": _path(FOLDER_MFG_INV, "wms_inbtrans_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_INV, "wms_inbtrans_analyzer.sql"),
        "description": "Analyzes Warehouse Management System (WMS) inbound transactions, putaway strategies, and receiving processing.",
        "keywords": ["wms", "warehouse management", "putaway", "inbound", "wms receiving", "lot tracking"],
        "severity_mappings": {
            "putaway error": "HIGH",
            "receiving error": "HIGH",
        },
        "mos_doc_id": "1483738.1",
    },
    "wsh": {
        "id": "wsh",
        "name": "Shipping Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "WSH",
        "analyze_file": _path(FOLDER_MFG_OM, "wsh_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_OM, "wsh_analyzer.sql"),
        "description": "Analyzes Oracle Shipping (WSH) delivery processing, shipping transactions, freight calculation, and manifest errors.",
        "keywords": ["shipping", "wsh", "delivery", "ship confirm", "freight", "manifest", "carrier", "shipping transaction"],
        "severity_mappings": {
            "delivery error": "HIGH",
            "ship confirm failure": "CRITICAL",
            "freight error": "MEDIUM",
        },
        "mos_doc_id": "1483739.1",
    },
    "wsh_stops": {
        "id": "wsh_stops",
        "name": "Shipping Stops Analyzer",
        "module": MODULE_MANUFACTURING,
        "sub_module": "WSH",
        "analyze_file": _path(FOLDER_MFG_OM, "wsh_stops_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_OM, "wsh_stops_analyzer.sql"),
        "description": "Analyzes shipping trip stops, open stops, stop close processing, and in-transit inventory issues.",
        "keywords": ["shipping stop", "trip stop", "in transit", "stop close", "wsh stop"],
        "severity_mappings": {
            "open stop": "HIGH",
            "in transit issue": "MEDIUM",
        },
        "mos_doc_id": "1483740.1",
    },

    # =========================================================================
    # HCM (04_Human_Capital_Management_Analyzers)
    # =========================================================================
    "ame": {
        "id": "ame",
        "name": "AME Approvals Analyzer",
        "module": MODULE_HCM,
        "sub_module": "AME",
        "analyze_file": _path(FOLDER_HCM, "ame_analyze.sql"),
        "analyzer_file": _path(FOLDER_HCM, "ame_analyzer.sql"),
        "description": "Analyzes Approval Management Engine (AME) rules, conditions, actions, and approval workflow configuration.",
        "keywords": ["ame", "approval management", "approval rule", "approval condition", "approver", "action type"],
        "severity_mappings": {
            "rule conflict": "CRITICAL",
            "missing approver": "HIGH",
            "infinite loop": "CRITICAL",
        },
        "mos_doc_id": "1483741.1",
    },
    "appraisal": {
        "id": "appraisal",
        "name": "Performance Appraisal Analyzer",
        "module": MODULE_HCM,
        "sub_module": "PERF",
        "analyze_file": _path(FOLDER_HCM, "appraisal_analyze.sql"),
        "analyzer_file": _path(FOLDER_HCM, "appraisal_analyzer.sql"),
        "description": "Analyzes Performance Appraisal processing, appraisal template issues, and review cycle configuration.",
        "keywords": ["appraisal", "performance review", "performance management", "review cycle", "appraisal template"],
        "severity_mappings": {
            "appraisal error": "MEDIUM",
            "template issue": "MEDIUM",
        },
        "mos_doc_id": "1483742.1",
    },
    "ben": {
        "id": "ben",
        "name": "Benefits Analyzer",
        "module": MODULE_HCM,
        "sub_module": "BEN",
        "analyze_file": _path(FOLDER_HCM, "ben_analyze.sql"),
        "analyzer_file": _path(FOLDER_HCM, "ben_analyzer.sql"),
        "description": "Analyzes Oracle Benefits plan setup, eligibility rules, enrollment processing, and benefits administration issues.",
        "keywords": ["benefits", "ben", "plan", "eligibility", "enrollment", "open enrollment", "life event"],
        "severity_mappings": {
            "enrollment error": "HIGH",
            "eligibility error": "HIGH",
            "plan setup error": "MEDIUM",
        },
        "mos_doc_id": "1483743.1",
    },
    "hcm_person": {
        "id": "hcm_person",
        "name": "HCM Person Analyzer",
        "module": MODULE_HCM,
        "sub_module": "HR",
        "analyze_file": _path(FOLDER_HCM, "hcm_person_analyze.sql"),
        "analyzer_file": _path(FOLDER_HCM, "hcm_person_analyzer.sql"),
        "description": "Analyzes HCM person records, person type assignments, duplicate persons, and person data integrity.",
        "keywords": ["hcm person", "person record", "employee record", "person type", "duplicate person"],
        "severity_mappings": {
            "duplicate person": "HIGH",
            "data integrity error": "HIGH",
        },
        "mos_doc_id": "1483744.1",
    },
    "hr": {
        "id": "hr",
        "name": "HR Core Analyzer",
        "module": MODULE_HCM,
        "sub_module": "HR",
        "analyze_file": _path(FOLDER_HCM, "hr_analyze.sql"),
        "analyzer_file": _path(FOLDER_HCM, "hr_analyzer.sql"),
        "description": "Analyzes HR Core setup, organization structures, positions, grades, and HR configuration issues.",
        "keywords": ["hr core", "organization", "position", "grade", "hr setup", "business group", "job"],
        "severity_mappings": {
            "org structure error": "HIGH",
            "setup error": "MEDIUM",
        },
        "mos_doc_id": "1483745.1",
    },
    "otl": {
        "id": "otl",
        "name": "Oracle Time & Labor Analyzer",
        "module": MODULE_HCM,
        "sub_module": "OTL",
        "analyze_file": _path(FOLDER_HCM, "otl_analyze.sql"),
        "analyzer_file": _path(FOLDER_HCM, "otl_analyzer.sql"),
        "description": "Analyzes Oracle Time & Labor (OTL) timecard processing, approval workflow, payroll integration, and time policy setup.",
        "keywords": ["time labor", "otl", "timecard", "time entry", "time policy", "payroll integration", "hxc"],
        "severity_mappings": {
            "timecard error": "HIGH",
            "approval stuck": "CRITICAL",
            "payroll integration error": "CRITICAL",
        },
        "mos_doc_id": "1483746.1",
    },
    "pay": {
        "id": "pay",
        "name": "Payroll Analyzer",
        "module": MODULE_HCM,
        "sub_module": "PAY",
        "analyze_file": _path(FOLDER_HCM, "pay_analyze.sql"),
        "analyzer_file": _path(FOLDER_HCM, "pay_analyzer.sql"),
        "description": "Analyzes Payroll processing, payroll runs, element configuration, payroll balances, and tax withholding setup.",
        "keywords": ["payroll", "pay run", "payroll processing", "element", "salary", "deduction", "tax withholding", "payroll balance"],
        "severity_mappings": {
            "payroll run error": "CRITICAL",
            "balance error": "CRITICAL",
            "element error": "HIGH",
        },
        "mos_doc_id": "1483747.1",
    },

    # =========================================================================
    # CRM (05_Customer_Relationship_Management_Analyzers)
    # =========================================================================
    "cn": {
        "id": "cn",
        "name": "Incentive Compensation Analyzer",
        "module": MODULE_CRM,
        "sub_module": "CN",
        "analyze_file": _path(FOLDER_CRM, "cn_analyze.sql"),
        "analyzer_file": _path(FOLDER_CRM, "cn_analyzer.sql"),
        "description": "Analyzes Incentive Compensation (CN) plan setup, calculation processing, payment batches, and commission disputes.",
        "keywords": ["incentive compensation", "cn", "commission", "bonus", "sales compensation", "calculation"],
        "severity_mappings": {
            "calculation error": "CRITICAL",
            "payment error": "HIGH",
            "plan error": "HIGH",
        },
        "mos_doc_id": "1483748.1",
    },
    "csd": {
        "id": "csd",
        "name": "Depot Repair Analyzer",
        "module": MODULE_CRM,
        "sub_module": "CSD",
        "analyze_file": _path(FOLDER_CRM, "csd_analyze.sql"),
        "analyzer_file": _path(FOLDER_CRM, "csd_analyzer.sql"),
        "description": "Analyzes Depot Repair (CSD) service order processing, repair jobs, and service order workflow.",
        "keywords": ["depot repair", "csd", "repair order", "service order", "repair job"],
        "severity_mappings": {
            "repair error": "HIGH",
            "workflow stuck": "HIGH",
        },
        "mos_doc_id": "1483749.1",
    },
    "csf": {
        "id": "csf",
        "name": "Field Service Analyzer",
        "module": MODULE_CRM,
        "sub_module": "CSF",
        "analyze_file": _path(FOLDER_CRM, "csf_analyze.sql"),
        "analyzer_file": _path(FOLDER_CRM, "csf_analyzer.sql"),
        "description": "Analyzes Field Service (CSF) task scheduling, debrief processing, parts management, and technician assignments.",
        "keywords": ["field service", "csf", "service task", "debrief", "technician", "scheduling"],
        "severity_mappings": {
            "scheduling error": "HIGH",
            "debrief error": "HIGH",
        },
        "mos_doc_id": "1483750.1",
    },
    "ib_txnerr": {
        "id": "ib_txnerr",
        "name": "Install Base Analyzer",
        "module": MODULE_CRM,
        "sub_module": "CSI",
        "analyze_file": _path(FOLDER_CRM, "ib_txnerr_analyze.sql"),
        "analyzer_file": _path(FOLDER_CRM, "ib_txnerr_analyzer.sql"),
        "description": "Analyzes Install Base (IB/CSI) transaction errors, instance tracking, and service contract linkages.",
        "keywords": ["install base", "ib", "csi", "instance", "product tracking", "service contract instance"],
        "severity_mappings": {
            "transaction error": "HIGH",
            "instance error": "HIGH",
        },
        "mos_doc_id": "1483751.1",
    },
    "ip_change": {
        "id": "ip_change",
        "name": "IP Change Analyzer",
        "module": MODULE_CRM,
        "sub_module": "IP",
        "analyze_file": _path(FOLDER_MFG_PROC, "ip_change_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_PROC, "ip_change_analyzer.sql"),
        "description": "Analyzes iProcurement change order processing, change request workflow, and approval routing.",
        "keywords": ["ip change", "change order", "change request", "iprocurement change"],
        "severity_mappings": {
            "change error": "HIGH",
            "workflow stuck": "HIGH",
        },
        "mos_doc_id": "1483752.1",
    },
    "ip_item": {
        "id": "ip_item",
        "name": "IP Item Analyzer",
        "module": MODULE_CRM,
        "sub_module": "IP",
        "analyze_file": _path(FOLDER_MFG_PROC, "ip_item_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_PROC, "ip_item_analyzer.sql"),
        "description": "Analyzes iProcurement item catalog, content zones, shopping cart items, and catalog management.",
        "keywords": ["iprocurement item", "catalog", "shopping cart", "content zone", "catalog item"],
        "severity_mappings": {
            "catalog error": "MEDIUM",
            "item sync error": "HIGH",
        },
        "mos_doc_id": "1483753.1",
    },
    "irec": {
        "id": "irec",
        "name": "iRecruitment Analyzer",
        "module": MODULE_CRM,
        "sub_module": "IRC",
        "analyze_file": _path(FOLDER_FIN, "irec_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "irec_analyzer.sql"),
        "description": "Analyzes iRecruitment (IRC) job posting, application processing, and recruitment workflow.",
        "keywords": ["irecruitment", "irc", "recruitment", "job posting", "applicant", "hiring"],
        "severity_mappings": {
            "workflow error": "HIGH",
            "posting error": "MEDIUM",
        },
        "mos_doc_id": "1483754.1",
    },
    "isp_setup": {
        "id": "isp_setup",
        "name": "iSupplier Setup Analyzer",
        "module": MODULE_CRM,
        "sub_module": "ISP",
        "analyze_file": _path(FOLDER_MFG_PROC, "isp_setup_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_PROC, "isp_setup_analyzer.sql"),
        "description": "Analyzes iSupplier Portal setup, supplier user registration, profile setup, and portal access issues.",
        "keywords": ["isupplier", "supplier portal", "supplier user", "supplier registration", "portal access"],
        "severity_mappings": {
            "access error": "HIGH",
            "registration error": "MEDIUM",
        },
        "mos_doc_id": "1483755.1",
    },
    "ocm": {
        "id": "ocm",
        "name": "Oracle Collections Management Analyzer",
        "module": MODULE_CRM,
        "sub_module": "OCM",
        "analyze_file": _path(FOLDER_FIN, "ocm_analyze.sql"),
        "analyzer_file": _path(FOLDER_FIN, "ocm_analyzer.sql"),
        "description": "Analyzes Oracle Collections Management setup, dunning plans, and collections strategy configuration.",
        "keywords": ["ocm", "collections management", "dunning", "collections strategy", "collections setup"],
        "severity_mappings": {
            "strategy error": "MEDIUM",
            "setup error": "HIGH",
        },
        "mos_doc_id": "1483756.1",
    },
    "oks_billing": {
        "id": "oks_billing",
        "name": "Service Contracts Billing Analyzer",
        "module": MODULE_CRM,
        "sub_module": "OKS",
        "analyze_file": _path(FOLDER_CRM, "oks_billing_analyze.sql"),
        "analyzer_file": _path(FOLDER_CRM, "oks_billing_analyzer.sql"),
        "description": "Analyzes Oracle Service Contracts (OKS) billing, invoice generation, contract renewal, and billing schedule.",
        "keywords": ["service contracts", "oks", "contract billing", "contract renewal", "billing schedule"],
        "severity_mappings": {
            "billing error": "HIGH",
            "renewal error": "HIGH",
        },
        "mos_doc_id": "1483757.1",
    },
    "osn_setup": {
        "id": "osn_setup",
        "name": "Oracle Social Network Analyzer",
        "module": MODULE_CRM,
        "sub_module": "OSN",
        "analyze_file": _path(FOLDER_MFG_PROC, "osn_setup_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_PROC, "osn_setup_analyzer.sql"),
        "description": "Analyzes Oracle Social Network (OSN) integration setup, collaboration configuration, and connection health.",
        "keywords": ["osn", "social network", "collaboration", "social", "osn setup"],
        "severity_mappings": {
            "integration error": "HIGH",
            "setup error": "MEDIUM",
        },
        "mos_doc_id": "1483758.1",
    },
    "ozf_sla": {
        "id": "ozf_sla",
        "name": "OZF SLA Analyzer",
        "module": MODULE_CRM,
        "sub_module": "OZF",
        "analyze_file": _path(FOLDER_CRM, "ozf_sla_unprocessed_trx_analyze.sql"),
        "analyzer_file": _path(FOLDER_CRM, "ozf_sla_unprocessed_trx_analyzer.sql"),
        "description": "Analyzes Oracle Trade Management (OZF) unprocessed SLA transactions and accrual accounting issues.",
        "keywords": ["ozf", "trade management", "accrual", "sla ozf", "trade promotion", "deduction"],
        "severity_mappings": {
            "unprocessed transaction": "HIGH",
            "accrual error": "HIGH",
        },
        "mos_doc_id": "1483759.1",
    },
    "p2p": {
        "id": "p2p",
        "name": "Procure-to-Pay Analyzer",
        "module": MODULE_CRM,
        "sub_module": "P2P",
        "analyze_file": _path(FOLDER_MFG_PROC, "p2p_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_PROC, "p2p_analyzer.sql"),
        "description": "Analyzes end-to-end Procure-to-Pay (P2P) cycle health, integration points, and cross-module issues.",
        "keywords": ["p2p", "procure to pay", "requisition", "purchase order", "receiving", "invoice", "payment"],
        "severity_mappings": {
            "cycle break": "CRITICAL",
            "integration error": "HIGH",
        },
        "mos_doc_id": "1483760.1",
    },
    "qot": {
        "id": "qot",
        "name": "Quoting Analyzer",
        "module": MODULE_CRM,
        "sub_module": "QOT",
        "analyze_file": _path(FOLDER_CRM, "qot_analyze.sql"),
        "analyzer_file": _path(FOLDER_CRM, "qot_analyzer.sql"),
        "description": "Analyzes Oracle Quoting (QOT) quote processing, pricing, and quote-to-order conversion.",
        "keywords": ["quoting", "qot", "quote", "sales quote", "quote approval", "pricing"],
        "severity_mappings": {
            "quote error": "HIGH",
            "pricing error": "MEDIUM",
        },
        "mos_doc_id": "1483761.1",
    },
    "qp_all": {
        "id": "qp_all",
        "name": "Advanced Pricing Analyzer",
        "module": MODULE_CRM,
        "sub_module": "QP",
        "analyze_file": _path(FOLDER_MFG_OM, "qp_all_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_OM, "qp_all_analyzer.sql"),
        "description": "Analyzes Advanced Pricing (QP) setup, price lists, modifiers, qualifiers, and pricing engine performance.",
        "keywords": ["advanced pricing", "qp", "price list", "modifier", "pricing engine", "discount", "surcharge"],
        "severity_mappings": {
            "pricing error": "HIGH",
            "price list error": "HIGH",
            "engine performance": "MEDIUM",
        },
        "mos_doc_id": "1483762.1",
    },
    "qp_line": {
        "id": "qp_line",
        "name": "Advanced Pricing Lines Analyzer",
        "module": MODULE_CRM,
        "sub_module": "QP",
        "analyze_file": _path(FOLDER_MFG_OM, "qp_line_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_OM, "qp_line_analyzer.sql"),
        "description": "Analyzes Advanced Pricing price list line data integrity, invalid lines, and pricing attributes.",
        "keywords": ["pricing lines", "price list line", "qp line", "pricing attribute", "price break"],
        "severity_mappings": {
            "invalid line": "HIGH",
            "attribute error": "MEDIUM",
        },
        "mos_doc_id": "1483763.1",
    },
    "clm": {
        "id": "clm",
        "name": "Contract Lifecycle Management Analyzer",
        "module": MODULE_CRM,
        "sub_module": "CLM",
        "analyze_file": _path(FOLDER_MFG_PROC, "clm_analyze.sql"),
        "analyzer_file": _path(FOLDER_MFG_PROC, "clm_analyzer.sql"),
        "description": "Analyzes Contract Lifecycle Management (CLM) contract processing, IDV awards, CLM approvals, and contract modifications.",
        "keywords": ["clm", "contract lifecycle", "contract management", "idv", "award", "contract modification"],
        "severity_mappings": {
            "contract error": "HIGH",
            "approval stuck": "CRITICAL",
        },
        "mos_doc_id": "1483764.1",
    },
}


def get_analyzer(analyzer_id: str) -> Optional[Dict[str, Any]]:
    """Retrieve a single analyzer by ID."""
    return ANALYZER_REGISTRY.get(analyzer_id)


def get_analyzers_by_module(module: str) -> List[Dict[str, Any]]:
    """Return all analyzers belonging to a given module."""
    return [a for a in ANALYZER_REGISTRY.values() if a["module"] == module]


def search_analyzers(keywords: List[str]) -> List[Dict[str, Any]]:
    """
    Search analyzers by keywords (case-insensitive substring match
    against name, description, sub_module, and keyword list).
    Returns list sorted by relevance (most matches first).
    """
    query_lower = [kw.lower() for kw in keywords]
    scores: Dict[str, int] = {}

    for aid, a in ANALYZER_REGISTRY.items():
        score = 0
        searchable = (
            a["name"].lower()
            + " "
            + a["description"].lower()
            + " "
            + a["sub_module"].lower()
            + " "
            + " ".join(a["keywords"])
            + " "
            + a["module"].lower()
        )
        for kw in query_lower:
            if kw in searchable:
                score += 1
        if score > 0:
            scores[aid] = score

    return sorted(
        [ANALYZER_REGISTRY[aid] for aid in scores],
        key=lambda a: scores[a["id"]],
        reverse=True,
    )


def get_all_modules() -> List[str]:
    """Return list of unique module names."""
    return sorted({a["module"] for a in ANALYZER_REGISTRY.values()})


def get_analyzer_count() -> int:
    """Return total number of registered analyzers."""
    return len(ANALYZER_REGISTRY)


# Knowledge base: common problem keywords → list of recommended analyzer IDs
PROBLEM_TO_ANALYZERS: Dict[str, List[str]] = {
    "ap_invoices_stuck": ["cp", "ap_accounting", "ap_inv_tax", "ap_period_close", "workflow"],
    "gl_period_close": ["gl_hc", "ap_period_close", "ar_periodclose", "cst_periodclose", "fa"],
    "concurrent_manager_down": ["cp", "mon", "workflow"],
    "workflow_notifications_not_sent": ["workflow", "bip", "cp", "mon"],
    "month_end_close": ["gl_hc", "ap_period_close", "ar_periodclose", "fa", "cst_periodclose", "ce"],
    "payroll_issues": ["pay", "otl", "ame", "hr"],
    "inventory_negative_balance": ["inv_trans", "cst_reconciliation", "inv_counting"],
    "order_stuck": ["om", "om_order", "cp", "workflow"],
    "supplier_payment_issues": ["ap_sup", "iby_fd", "ap_accounting", "ap_period_close"],
    "tax_errors": ["ap_inv_tax", "o2c_ebtax", "sla_setup"],
    "receiving_issues": ["rcv_podata", "inv_trans", "po_doc"],
    "cost_variance": ["cst_reconciliation", "cst_periodclose", "wip", "bom"],
    "mrp_planning_issues": ["ascp_collections", "ascp_perf", "bom", "inv_trans"],
    "system_performance": ["mon", "cp"],
    "ar_receipts_stuck": ["ar_rct", "ar_periodclose", "workflow", "cp"],
    "fixed_assets_depreciation": ["fa", "sla_setup", "gl_hc"],
    "purchasing_approval_stuck": ["po_approval", "ame", "workflow", "cp"],
    "shipping_issues": ["wsh", "wsh_stops", "om_order", "inv_trans"],
    "project_costing_issues": ["pa_pjc_expend", "pa_pjf_foundation", "sla_setup"],
    "benefits_enrollment": ["ben", "ame", "workflow"],
}
